service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends curl docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:

- bash ./gradlew war >/dev/null
- docker-compose -f docker-compose-gradle.yaml build
- docker-compose -f docker-compose-gradle.yaml up &
- wait_for 8080 5005 9990
- sleep 25
- http :8080/app data=ololo
- http :8080/app data=trololo
- http :8080/app data=olo
- http :8080/app data=gradle
- http :8080/app
- docker-compose -f docker-compose-gradle.yaml down -v


- docker rm -f -v $(docker ps -a|grep -v CONTAINER|awk '{print $1}') || true
- docker rmi -f $(docker images| grep -v daggerok|grep -v TAG|awk '{print $3}') || true
- docker volume rm $(docker volume ls|grep -v DRIVER|awk '{print $2}') || true
- bash ./mvnw -U >/dev/null
- docker-compose -f docker-compose-maven.yaml build
- docker-compose -f docker-compose-maven.yaml up &
- wait_for 8080 5005 9990
- sleep 20
- http :8080/app data=ololo
- http :8080/app data=trololo
- http :8080/app data=olo
- http :8080/app data=maven
- http :8080/app
- docker-compose -f docker-compose-maven.yaml down -v

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
